20-styling-intro/school-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cohorts, only: [:new, :create, :show, :index], path: 'batches'
  # resources :cohorts, except: [:edit, :update, :destroy]
  resources :students, only: [:new, :create, :show, :edit, :update]

  root to: 'cohorts#index'
end

20-styling-intro/school-app/app/models/cohort.rb
class Cohort < ApplicationRecord
    has_many :students

    validates :name, { presence: true, uniqueness: true }
end

20-styling-intro/school-app/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort
end

20-styling-intro/school-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

20-styling-intro/school-app/app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(name: params[:name])
    if @cohort.save
      redirect_to cohorts_path
    else
      render :new
    end
  end

  def index
    @cohorts = Cohort.all
  end

end

20-styling-intro/school-app/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to student_path(@student)
    else
      render :edit
    end
  end

  private
  def student_params
    params.require(:student).permit(:name, :image_url, :favorite_movie, :cohort_id)
  end

end

20-styling-intro/school-app/app/helpers/application_helper.rb
module ApplicationHelper
end

20-styling-intro/school-app/app/views/application/_navbar.html.erb
<div class="ui secondary menu">
  <%= link_to("Home", root_path, class: "item active") %>
  <%= link_to("Cohorts", cohorts_path, class: "item") %>
  <%= link_to("Students", students_path, class: "item") %>
  <div class="right menu">
    <div class="item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
    <a class="ui item">
      Logout
    </a>
  </div>
</div>

20-styling-intro/school-app/app/views/cohorts/index.html.erb
<h1>List of Cohorts</h1>

<ul>
  <% @cohorts.each do |cohort| %>
    <li><%= cohort.name %></li>
  <% end %>
</ul>

<!-- <a href="/cohorts/new">Add a new cohort</a> -->
<%= link_to("Add a new cohort", new_cohort_path) %>

20-styling-intro/school-app/app/views/cohorts/new.html.erb
<h1>Add a new Cohort</h1>

<% if @cohort.errors %>
  <ul>
    <% @cohort.errors.full_messages.each do |msg| %>
      <li style="color: red;"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<!-- <form action="<%= cohorts_path %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  <input type="text" name="name" value="<%= @cohort.name %>" />
  <input type="submit" value="Add Cohort" />
</form> %>
-->

<%= form_tag(cohorts_path, method: :post) do %>
  <%= text_field_tag("name", @cohort.name) %>
  <%= submit_tag("Add Cohort") %>
<% end %>

<!--
<% byebug %>
<%= form_for(@cohort) do |f| %>
  <%= f.text_field(:name) %>
  <%= f.submit("Add Cohort") %>
<% end %>
-->

20-styling-intro/school-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeSchool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css" />
  </head>

  <body>
    <%= render("navbar") %>
    <%= yield %>
  </body>
</html>

20-styling-intro/school-app/app/views/students/_form.html.erb
<% if @student.errors %>
  <h2>Form Errors</h2>
  <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li style="color: red;"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@student) do |f| %>
  <%= f.text_field(:name, placeholder: "Name") %>
  <%= f.text_field(:image_url) %>
  <%= f.text_field(:favorite_movie) %>
  <%= f.collection_select(:cohort_id, Cohort.all, :id, :name) %>
  <%= f.submit %>
<% end %>

20-styling-intro/school-app/app/views/students/edit.html.erb
<h1>Edit a current student</h1>

<%= render("form") %>

<%= link_to("All Students", students_path) %>


<!-- 
<%= form_tag(student_path(@student), method: :patch) do %>
  <%= text_field_tag("name", @student.name, placeholder: "Name") %>
  <%= text_field_tag("image_url", @student.image_url, placeholder: "Image") %>
  <%= text_field_tag("favorite_movie", @student.favorite_movie, placeholder: "Movie") %>
  <%= collection_select(nil, :cohort_id, Cohort.all, :id, :name) %>
  <input type="submit" value="Update Student" />
<% end %>
-->

20-styling-intro/school-app/app/views/students/new.html.erb
<h1>Add a new Student</h1>

<%= render("form") %>

<%= link_to("All Students", students_path) %>

20-styling-intro/school-app/app/views/students/show.html.erb
<div class="ui card">
  <div class="content">
    <div class="right floated meta"><%= time_ago_in_words(@student.created_at) %></div>
    <%= @student.name %>
  </div>
  <div class="image">
    <img src="<%= @student.image_url %>">
  </div>
  <div class="content">
    <i class="comment icon"></i>
    Cohort: <%= link_to(@student.cohort.name, cohort_path(@student.cohort)) %>
  </div>
  <div class="extra content">
    <div class="ui large transparent left icon input">
      <i class="heart outline icon"></i>
    </div>
    <span class="right floated">Loves: <%= @student.favorite_movie %></span>
  </div>
</div>

<%= link_to("Edit Student", edit_student_path(@student)) %>